package zollernextras.blocks;

import net.minecraft.block.Block;
import zollernextras.blocks.crops.CropBlock;
import zollernextras.blocks.ores.AmaranthOre;
import zollernextras.blocks.ores.EnderShardOre;
import zollernextras.blocks.ores.FueltoniumOre;
import zollernextras.blocks.ores.GemOre;
import zollernextras.blocks.ores.SuperChargedCoalOre;
import zollernextras.blocks.ores.ZincOre;
import zollernextras.blocks.ores.ender.EnderAmaranthOre;
import zollernextras.blocks.ores.ender.EnderFueltoniumOre;
import zollernextras.blocks.ores.ender.EnderSpcOre;
import zollernextras.blocks.ores.ender.EnderZincOre;
import zollernextras.blocks.ores.nether.NetherAmaranthOre;
import zollernextras.blocks.ores.nether.NetherEnderShardOre;
import zollernextras.blocks.ores.nether.NetherFueltoniumOre;
import zollernextras.blocks.ores.nether.NetherSPCOre;
import zollernextras.blocks.ores.nether.NetherZincOre;
import zollernextras.blocks.sirens.DiamondSiren;
import zollernextras.blocks.sirens.EmeraldSiren;
import zollernextras.blocks.sirens.GoldSiren;
import zollernextras.blocks.sirens.IronSiren;
import zollernextras.items.ItemList;
import zollernextras.lib.enums.State;
import cpw.mods.fml.common.registry.GameRegistry;

public class BlockList {
	
	public static Block betterGlass = new BetterGlass();
	public static Block spcOre = new SuperChargedCoalOre();
	public static Block shinestone = new Shinestone();
	public static Block fueltonium = new FueltoniumOre();
	public static Block barrier = new BarrierBlock();
	public static Block icySand = new IcySand();
	public static Block icyStone = new IcySandstone();
	public static Block enderShardOre = new EnderShardOre();
	public static Block amaranthOre = new AmaranthOre();
	public static Block slimeBlock = new SlimeBlock();
	public static Block redShroomBlock = new RedshroomBlock();
	public static Block redShroomStem = new RedshroomStem();
	public static Block redRock = new RedRock();
	public static Block redRockCobble = new RedRockCobble();
	public static Block redRockBrick = new RedRockBricks();
	public static Block betterGrass = new BetterGrass();
	public static Block swampClay = new SwampClay();
	public static Block canyonRock = new CanyonRock();
	public static Block badStone = new BadStone();
	public static Block amaranthBlock = new AmaranthBlock();
	public static Block spcBlock = new SPCBlock();
	public static Block fueltoniumBlock = new FueltoniumBlock();
	public static Block zincOre = new ZincOre();
	public static Block zincBlock = new ZincBlock();
	public static Block zollerniumBlock = new ZollerniumBlock();
	public static Block seaLamp = new SeaLamp();
	public static Block ironSiren = new IronSiren(State.OFF);
	public static Block ironSirenON = new IronSiren(State.ON);
	public static Block goldSiren = new GoldSiren(State.OFF);
	public static Block goldSirenON = new GoldSiren(State.ON);
	public static Block diamondSiren = new DiamondSiren(State.OFF);
	public static Block diamondSirenON = new DiamondSiren(State.ON);
	public static Block emeraldSiren = new EmeraldSiren(State.OFF);
	public static Block emeraldSirenON = new EmeraldSiren(State.ON);
	public static Block shinestoneCrystal = new ShinestoneCrystal();
	public static Block shinestoneBricks = new ShinestoneBricks();
	public static Block fuelNetherOre = new NetherFueltoniumOre();
	public static Block spcNetherOre = new NetherSPCOre();
	public static Block amaranthNetherOre = new NetherAmaranthOre();
	public static Block zincNetherOre = new NetherZincOre();
	public static Block enderShardNetherOre = new NetherEnderShardOre();
	public static Block amberOre = new GemOre("amberore", ItemList.amber);
	public static Block azuriteOre = new GemOre("azuriteore", ItemList.azurite);
	public static Block aquamarineOre = new GemOre("aquaore",
			ItemList.aquamarine);
	public static Block garnetOre = new GemOre("garnetore", ItemList.garnet);
	public static Block topazOre = new GemOre("topazore", ItemList.topaz);
	public static Block opalOre = new GemOre("opalore", ItemList.opal);
	public static Block enderiteOre = new GemOre("enderiteore",
			ItemList.enderite);
	public static Block caveMarbleWhite = new CaveMarble("marble");
	public static Block caveMarbleBlack = new CaveMarble("blackmarble");
	public static Block brimStone = new Brimstone();
	public static Block netherDirt = new NetherDirt();
	public static Block enderAmaranthOre = new EnderAmaranthOre();
	public static Block enderFnOre = new EnderFueltoniumOre();
	public static Block enderSpcOre = new EnderSpcOre();
	public static Block enderZincOre = new EnderZincOre();
	public static Block garnet = new GemBlock("garnet");
	public static Block fireGarnet = new GemBlock("firegarnet");
	public static Block aqua = new GemBlock("aqua");
	public static Block icyAqua = new GemBlock("icyaqua");
	public static Block amber = new GemBlock("amber");
	public static Block staticAmber = new GemBlock("staticamber");
	public static Block enderite = new GemBlock("enderite");
	public static Block opal = new GemBlock("opal");
	public static Block enderOpal = new GemBlock("enderopal");
	public static Block topaz = new GemBlock("topaz");
	public static Block azurite = new GemBlock("azurite");
	public static Block shiniumBlock = new GemBlock("shinium");
	public static Block goldenAnvil = new GoldenAnvil();
	public static Block babyEnderDragonEgg = new BabyDragonEgg();
	public static Block blueberry = new CropBlock("blueberry");
	public static Block blackberry = new CropBlock("blackberry");
	public static Block grape = new CropBlock("grape");
	public static Block strawberry = new CropBlock("strawberry");
	
	public static void init() {
		addBlock(betterGlass, "Stylish Glass");
		addBlock(amaranthOre, "Amaranth Ore");
		addBlock(spcOre, "Super Charged Coal Ore");
		addBlock(enderShardOre, "Ender Shard Ore");
		addBlock(fueltonium, "Fueltonium Ore");
		addBlock(amberOre, "Amber Ore");
		addBlock(azuriteOre, "Azurite Ore");
		addBlock(aquamarineOre, "Aquamarine Ore");
		addBlock(garnetOre, "Garnet Ore");
		addBlock(topazOre, "Topaz Ore");
		addBlock(opalOre, "Opal Ore");
		addBlock(enderiteOre, "Enderite Ore");
		addBlock(fuelNetherOre, "Nether Fueltonium Ore");
		addBlock(spcNetherOre, "Nether Super Charged Coal Ore");
		addBlock(amaranthNetherOre, "Nether Amaranth Ore");
		addBlock(zincNetherOre, "Nether Zinc Ore");
		addBlock(enderShardNetherOre, "Nether Ender Shard Ore");
		addBlock(enderAmaranthOre, "Ender Amaranth Ore");
		addBlock(enderFnOre, "Ender Fueltonium Ore");
		addBlock(enderSpcOre, "Ender Super Charged Coal Ore");
		addBlock(enderZincOre, "Ender Zinc Ore");
		addBlock(amaranthBlock, "Amaranth Block");
		addBlock(spcBlock, "Super Charged Coal Block");
		addBlock(fueltoniumBlock, "Fueltonium Block");
		addBlock(zincBlock, "Zinc Block");
		addBlock(zollerniumBlock, "Zollernium Block");
		addBlock(zincOre, "Zinc Ore");
		addBlock(shinestone, "Shinestone");
		addBlock(shinestoneCrystal, "Shinestone Crystal");
		addBlock(shinestoneBricks, "Shinestone Bricks");
		addBlock(barrier, "Barrier Block");
		addBlock(icySand, "Icy Sand");
		addBlock(icyStone, "Icy Sandstone");
		addBlock(slimeBlock, "Slime Block");
		addBlock(redShroomBlock, "Redshroom Block");
		addBlock(redShroomStem, "Redshroom Stem");
		addBlock(redRock, "Redrock");
		addBlock(redRockCobble, "Redrock Cobble");
		addBlock(redRockBrick, "Redrock Bricks");
		addBlock(betterGrass, "Better Grass");
		addBlock(swampClay, "Swamp Clay");
		addBlock(canyonRock, "Canyon Rock");
		addBlock(badStone, "Bad Stone");
		addBlock(seaLamp, "Sea Lamp");
		addBlock(ironSiren, "Iron Siren");
		addBlock(goldSiren, "Gold Siren");
		addBlock(diamondSiren, "Diamond Siren");
		addBlock(emeraldSiren, "Emerald Siren");
		addBlock(caveMarbleWhite, "Cave Marble");
		addBlock(caveMarbleBlack, "Black Cave Marble");
		addBlock(brimStone, "Brimstone");
		addBlock(netherDirt, "Nether Dirt");
		addBlock(garnet, "Block of Garnet");
		addBlock(fireGarnet, "Block of Fire Garnet");
		addBlock(aqua, "Block of Aquamarine");
		addBlock(icyAqua, "Block of Icy Aquarmarine");
		addBlock(amber, "Block of Amber");
		addBlock(staticAmber, "Block of Static Amber");
		addBlock(enderite, "Block of Enderite");
		addBlock(opal, "Block of Opal");
		addBlock(enderOpal, "Block of Ender Opal");
		addBlock(topaz, "Block of Topaz");
		addBlock(azurite, "Block of Azurite");
		addBlock(shiniumBlock, "Block of Shinium");
		addBlock(goldenAnvil, "Golden Anvil");
		addBlock(babyEnderDragonEgg, "Baby Ender Dragon Egg");
		addBlock(blueberry, "Blueberries");
		addBlock(blackberry, "Blackberries");
		addBlock(grape, "Grapes");
		addBlock(strawberry, "Strawberries");
	}
	
	public static void addBlock(Block block, String name) {
		GameRegistry.registerBlock(block, name);
	}
}